# Generated by Django 2.0.7 on 2018-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HedgeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site1', models.CharField(max_length=255, verbose_name='site1')),
                ('site2', models.CharField(max_length=255, verbose_name='site2')),
                ('type1', models.CharField(max_length=255, verbose_name='type1')),
                ('type2', models.CharField(max_length=255, verbose_name='type2')),
            ],
            options={
                'verbose_name': '对冲订单',
                'verbose_name_plural': '对冲订单',
            },
        ),
    ]
